version: '3'

services:
  frontend:
    container_name: frontend
    build: ./
    restart: unless-stopped
    ports:
      - "4173:4173"
      - "5173:4173"
    networks:
      - network

networks:
  network:

volumes:
  postgres:
  statics: